/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg4;

import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class changeWindow extends javax.swing.JDialog {

    //Creación de variables
    public int sPosition;
    public int fPosition;
    public static int vec[];
    MainWindow ventana = new MainWindow();

    /**
     * En este bloque se determina el estado inical de las etiquetas y los botones.
     * Además se establece que la ventana aparezca en el centro de la pantalla.
     */
    public changeWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel1.setText("<html><p>A continuación, indique las dos posiciones que desea intercambiar.</p></html>");
        vec = MainWindow.vec;
        ventana = (MainWindow) parent;
    }

    changeWindow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveChange = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pos1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pos2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        endEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        saveChange.setText("Guardar cambio");
        saveChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangeActionPerformed(evt);
            }
        });

        jLabel2.setText("Posicion 1:");

        jLabel3.setText("Posición 2:");

        jLabel1.setText("jLabel1");

        endEdit.setText("Finalizar edición");
        endEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(saveChange)
                        .addGap(18, 18, 18)
                        .addComponent(endEdit)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChange)
                    .addComponent(endEdit))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Al pulsar este botón se extraen los textos de los TextField y se realizan
     * las diferentes comprobaciones que puedan generar error (valores que se salgan
     * de los límites del vector o ingresos no numéricos).
     * Luego, se toman dos posiciones de un vector y se intercambian
     * @param evt Identifica cuando el botón es pulsado e inicia las acciones internas del botón
     */
    private void saveChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangeActionPerformed
        String strNumber = pos2.getText();
        String strPos = pos1.getText();
        if (strPos.equals("") || strNumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, llene ambos campos antes de presionar el botón GUARDAR CAMBIO.");
        } else {
            try {
                sPosition = Integer.parseInt(strNumber);
                fPosition = Integer.parseInt(strPos);
                if (fPosition <= 0 || fPosition > vec.length) {
                    JOptionPane.showMessageDialog(null, "La primera posición ingresada está por fuera del tamaño del vector.");
                } else {
                    if (sPosition <= 0 || sPosition > vec.length) {
                        JOptionPane.showMessageDialog(null, "La segunda posición ingresada está por fuera del tamaño del vector.");
                    } else {
                        vec = ventana.positionExchange(vec, fPosition-1, sPosition-1);
                        pos2.setText("");
                        pos1.setText("");
                        JOptionPane.showMessageDialog(null, "Cambio hecho correctamente.");
                        ventana.showVector(vec, vec.length);    
                    }
                }
            } catch (NumberFormatException exception) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese únicamente valores numéricos.");
            }
        }
    }//GEN-LAST:event_saveChangeActionPerformed

    
    /**
     * Este botón cierra la ventana actual, volviendo a la ventana padre
     * @param evt Identifica cuando el botón es pulsado e inicia las acciones internas del botón
     */
    private void endEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endEditActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_endEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                changeWindow dialog = new changeWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField pos1;
    private javax.swing.JTextField pos2;
    private javax.swing.JButton saveChange;
    // End of variables declaration//GEN-END:variables
}
